import researchVillage from "../assets/research-village.jpg";
import { Link } from "react-router";
import { OverviewPage } from "./Overview";
import "../landing.css";

export function LandingPage() {
  return <div className="track-landing">
    <a className="landing-skip" href="#research-cycle">Skip to research workspace</a>
    <section className="landing-hero" aria-labelledby="landing-title">
      <img className="landing-art" src={researchVillage} alt="Illustrated coastal village with open workshops and two researchers studying plants beside the water." fetchPriority="high" width="2048" height="1143" />
      <div className="landing-shade" aria-hidden="true" />
      <nav className="landing-nav" aria-label="Main navigation">
        <Link className="landing-brand" to="/">fabryka<span>/ track</span></Link>
        <div className="landing-nav-links"><a href="#our-research">Our runs</a><a href="#why-track">Why Track</a><a href="#research-cycle">The workspace</a><Link to="/benchmark-results">Results</Link></div>
        <Link className="landing-nav-cta" to="/overview">Open Track ↗</Link>
      </nav>
      <div className="landing-intro"><p className="landing-kicker">FABRYKA TRACK / BUILT BY MODEL BUILDERS</p><h1 id="landing-title">Serious experiment tracking.<br />A pleasure to use.</h1><p className="landing-description">We’re building Track to make experiments easier to understand — from a first loss curve to the next model. We use it for our own training runs and SLM competition work, and share what we learn.</p><div className="landing-actions"><Link className="landing-action" to="/overview">Explore Track ↗</Link><a className="landing-action secondary" href="#why-track">Why we’re building it ↓</a></div></div>
      <div className="landing-caption"><span>FABRYKA TRACK / THE RESEARCH WORKSPACE</span><span>Built in Warsaw. Used in our own research.</span></div>
    </section>
    <div className="landing-ribbon"><span>FROM THE FIRST IDEA TO THE NEXT DISCOVERY</span><div><span>Data</span><i>→</i><span>Training</span><i>→</i><span>Evaluation</span><i>→</i><span>Learning</span></div></div>
    <main>
      <section className="landing-own-research" id="our-research" aria-labelledby="own-research-title">
        <div className="landing-own-intro"><p className="landing-kicker">OUR MODELS. OUR RUNS. THIS TRACKER.</p><h2 id="own-research-title">We use Track to build<br />our own models.</h2><p>Fabryka is a model-building lab. We train small language models, enter SLM competitions, and use Track to follow our own training runs and evaluate what we build.</p><p>We show the work behind the results: the training process, the experiments and the evaluations. You can follow how it’s done, then use the same tools for your own ideas.</p><Link className="landing-action" to="/benchmark-results">Explore our published experiments ↗</Link></div>
        <div className="landing-own-evidence"><Link to="/benchmark-results"><span>01 / SEE THE EVIDENCE</span><h3>Open the results. Follow the run.</h3><p>Published evaluations connect scores to the run, checkpoint and protocol behind them.</p><b>Browse published results ↗</b></Link><Link to="/guide"><span>02 / LEARN THE PROCESS</span><h3>See how a model gets made.</h3><p>Follow the training guide from preparing data to running and evaluating an experiment.</p><b>Read the training guide ↗</b></Link><Link to="/goals"><span>03 / FOLLOW THE QUESTIONS</span><h3>Understand what we’re trying next.</h3><p>Read the research goals and proposals that shape the next experiments.</p><b>Explore our research goals ↗</b></Link></div>
      </section>
      <section className="landing-story" id="why-track" aria-labelledby="why-track-title">
        <div><p className="landing-kicker">THE REASON WE’RE HERE</p><h2 id="why-track-title">A tracker you look<br />forward to opening.</h2></div>
        <div className="landing-story-copy"><p>Research happens in the details. A loss curve starts to drift. A promising run pulls ahead. A small configuration change turns out to matter. Your tracker is where you make sense of those moments and decide what to try next.</p><p>Neptune earned a loyal following among researchers who valued that experience. When its hosted service closed in March 2026 following its acquisition by OpenAI, they had to find a new home for their experiments. The data remaining in the hosted service was permanently deleted.</p><p>We’re building Fabryka Track for people who care about how that workspace feels. Checking a run should be straightforward. Comparing experiments should make differences clear. Following a question through your results should keep you focused as your history grows.</p><p>That takes care throughout the product: reliable logging, responsive queries, readable charts and useful defaults. These are the standards we’re building toward and testing against our own model-training work.</p><p>Our aim is a tracker that helps you see what happened, understand what changed, and choose your next experiment with confidence.</p><p className="landing-independence"><strong>An independent project.</strong> Fabryka Track is not affiliated with, endorsed by, or sponsored by Neptune.ai or OpenAI. References to Neptune explain our motivation, not a relationship between the companies.</p><a className="landing-story-source" href="https://web.archive.org/web/20260409174455/https://docs.neptune.ai/" target="_blank" rel="noopener noreferrer">Neptune’s shutdown notice · archived ↗</a></div>
      </section>
      <section className="landing-principles" aria-labelledby="principles-title"><p className="landing-kicker">WHAT WE’RE BUILDING TOWARD</p><h2 id="principles-title">Understand the run. Find the difference. Keep learning.</h2><div className="landing-principles-grid"><article><span>01 / PERFORMANCE</span><h3>Log what matters.</h3><p>A loss spike should be easy to investigate. We’re working toward responsive exploration of dense training metrics, with clear controls for smoothing and the detail shown on each chart.</p></article><article><span>02 / RESEARCH WORKFLOW</span><h3>Find what changed.</h3><p>Move from a curve to the configuration and checkpoint behind it. We’re working toward richer run queries and comparisons that keep meaningful differences in view.</p></article><article><span>03 / OWNERSHIP</span><h3>Keep your history.</h3><p>Track can run on your own infrastructure today. We’re building toward a straightforward path to export your research and use it elsewhere, without depending on our hosted service.</p></article></div><p className="landing-roadmap-note">These are our design goals. Today, Track supports self-hosting, run tracking, metrics, logs, checkpoints and run comparison. Large-scale storage and export improvements are still ahead.</p></section>
      <section className="landing-sustainability" id="licensing" aria-labelledby="licensing-title"><div><p className="landing-kicker">CONTRIBUTION & SUSTAINABILITY</p><h2 id="licensing-title">Room to contribute.<br />A business built to last.</h2></div><div><p>We want developers to be able to explore Track, experiment with it, and contribute improvements. We intend to choose licensing terms that make that possible.</p><p>Fabryka AI is a for-profit company. We want to earn a healthy, sustainable income from this work — enough to keep investing in the product, support its users, and pay the people building it.</p><p>We’re still working out how those goals fit together. We haven’t committed to a long-term licensing approach, pricing structure, or business model. We’ll share the details as we find a model that works for developers, users, and the company.</p></div></section>
      <div id="research-cycle"><div className="landing-section-intro"><p className="landing-kicker">AVAILABLE IN TRACK TODAY</p><h2>Follow the idea.<br />Keep what you learn.</h2><p>A dataset mix, a training run, a saved checkpoint, a test result. Track keeps the pieces together, so each experiment gives the next one a better starting point.</p></div><OverviewPage landing /></div>
    </main>
    <footer className="landing-footer"><Link className="landing-brand" to="/">fabryka<span>/ track</span></Link><p>See what happened. Decide what comes next.</p><div><a href="#licensing">Licensing & sustainability</a><Link to="/guide">Training guide</Link><Link to="/agents">For agents</Link><a href="https://fabryka.ai">Fabryka AI ↗</a></div><p className="landing-footer-independence">Fabryka Track is an independent Fabryka AI project. We are not affiliated with, endorsed by, or sponsored by Neptune.ai or OpenAI.</p></footer>
  </div>;
}
